### ISSUE TITLE
Missing vendor_compliance

### ISSUE THREAD

**Issue by itamar-marom** [dokc/operator-feature-matrix#9]
Under id `depau` there is no `vendor_compliance` section

**Comment by itamar-marom** [comment]
same under id `pgcnf`

**Comment by ahachete** [comment]
Thanks for raising this @itamar-marom 

Actually the `vendor_compliance` field is not meant to be compulsory. It is meant to be a clarification for vendor submissions if the `name`, `type` and `description` fields would not make it too obvious how vendors should submit their values.

For the cases you describe, I believe the field is not needed, specially being both types `boolean` and very clearly cut (IMO).

Do you believe they require further clarification? If so, would you mind suggesting a wording for it, ideally as a PR?

**Comment by itamar-marom** [comment]
I didn't understand this, but now it logically make sense 😅
I'll close this since it's not relevant.
